# Generated by Django 2.1.11 on 2019-08-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to='transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sales_tax_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sales_tax_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
