# Generated by Django 4.2.5 on 2023-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_transactiontag_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('travel', 'Travel'), ('house', 'House'), ('kollektiivi', 'Kollektiivi'), ('car', 'Car'), ('personal', 'Personal'), ('misc', 'Misc'), ('business', 'Business')], max_length=100, null=True),
        ),
    ]
