# Generated by Django 4.2.6 on 2023-10-19 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_valuation_value_per_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
