# Generated by Django 4.2.6 on 2023-10-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_accountingperiods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountingPeriods',
            new_name='AccountingPeriod',
        ),
    ]
