# Generated by Django 4.2.6 on 2023-10-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0011_account_notes_transactiontag_allocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiontag',
            old_name='allocation',
            new_name='allocation_credit',
        ),
        migrations.AddField(
            model_name='transactiontag',
            name='allocation_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
