# Generated by Django 4.2.6 on 2023-10-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0012_rename_allocation_transactiontag_allocation_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontag',
            name='percent',
        ),
    ]
