# Generated by Django 4.2.7 on 2023-11-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0014_transactiontag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=2, default=24, max_digits=20),
        ),
    ]
