# Generated by Django 5.0 on 2023-12-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0018_invoicetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetemplate',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
