# Generated by Django 5.0.4 on 2024-05-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0020_invoicetemplate_deposit_held'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('travel', 'Travel'), ('house', 'House'), ('kollektiivi', 'Kollektiivi'), ('car', 'Car'), ('personal', 'Personal'), ('misc', 'Misc'), ('business', 'Business'), ('design', 'DesignShop')], max_length=100, null=True),
        ),
    ]
