# Generated by Django 6.0.7 on 2026-08-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0026_tag_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="invoicetemplate",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("travel", "Travel"),
                    ("house", "House"),
                    ("kollektiivi", "Kollektiivi"),
                    ("car", "Car"),
                    ("personal", "Personal"),
                    ("misc", "Misc"),
                    ("business", "Business"),
                    ("design", "DesignShop"),
                    ("rental", "Rental"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="file",
            field=models.FileField(blank=True, default="", upload_to="transaction"),
        ),
    ]
