# Generated by Django 6.0.7 on 2026-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0027_alter_account_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactiontag",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
