from money.reports.views.by_month import *
from money.reports.views.by_year import *
from money.reports.views.consulting_quarters import *
from money.reports.views.consulting_annual import *
from money.reports.views.graph import *
from money.reports.views.bills import *
from money.reports.views.graph_investment import *
from money.reports.views.monthly_transactions import *
from money.reports.views.kollektiivi_monthly import *
from money.reports.views.tags_by_year import *
from money.reports.views.tag_detail import *
